version: "3.6"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    # ports:
    #   - "5000:5000"
    links:
      - datastore

  datastore:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo_store:/data/db
    ports:
      - '27017:27017'

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
    mongo_store:
